### ISSUE TITLE
No setup.sh script in the "scripts" folder

### ISSUE THREAD

**Issue by andylshort** [frebib/dotfiles#1]
The README lies!

"scripts\setup.sh" doesn't exist. Docs are out-of-date or you forgot to commit a file. ;)

**Comment by frebib** [comment]
I renamed the file but looks like I didn't update the readme. The file is now [scripts/configsetup](https://github.com/frebib/dotfiles/blob/master/scripts/configsetup). It's not finished mind you. I'll probably sort it out after the exam period!

**Comment by frebib** [comment]
I totally didn't have to edit that commit twice...
